import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
async function main(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'deadline-design-'));process.env.AMMA_STATE_PATH=path.join(dir,'state.json');process.env.AMMA_OFFLINE='true';process.env.AMMA_MOCK_INSTAGRAM='true';
 const {saveState,defaultState}=await import('../state');const {createDashboard}=await import('../dashboard/server');const state=defaultState();state.deadlineISO=new Date(Date.now()+17*3600000).toISOString();state.stage='calm';state.hostagePhoto=path.resolve('photos/aurafarmer.jpg');saveState(state);const before=fs.readFileSync(process.env.AMMA_STATE_PATH,'utf8');
 const server=createDashboard().listen(0,'127.0.0.1');await new Promise<void>(r=>server.on('listening',r));const base=`http://127.0.0.1:${(server.address() as any).port}`;
 const browser=await chromium.launch({headless:true,executablePath:fs.existsSync(chromium.executablePath())?undefined:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try{const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir,size:{width:1440,height:900}}});const page=await context.newPage();let posts=0;page.on('request',r=>{if(r.method()==='POST')posts++;});await page.goto(base);await page.waitForFunction(()=>document.getElementById('stage')?.textContent==='calm');await page.waitForFunction(()=>{const img=document.getElementById('vault-photo') as HTMLImageElement;return img.complete&&img.naturalWidth>0;});await page.locator('#replay').click();await page.waitForFunction(()=>document.getElementById('stage')?.textContent==='hostile',{},{timeout:32000});await page.screenshot({path:path.resolve('artifacts/claude-dashboard.png'),fullPage:true});await page.waitForFunction(()=>document.getElementById('stage')?.textContent==='fired',{},{timeout:10000});assert.equal(posts,0);assert.equal(fs.readFileSync(process.env.AMMA_STATE_PATH,'utf8'),before);assert(await page.locator('#mark-done').isHidden());await page.locator('#replay').click();await page.waitForFunction(()=>document.getElementById('stage')?.textContent==='calm');assert.equal(posts,0);const video=page.video();await context.close();await video?.saveAs(path.resolve('artifacts/Deadline_Hostage_30_second_replay.webm'));console.log('Design verified: all replay stages, return to live, zero writes, state unchanged. Video saved.');}finally{await browser.close();server.close();}
}main().catch(e=>{console.error(e);process.exitCode=1;});
