// Live state is read-only here except the explicit work-complete action.
const $=id=>document.getElementById(id), bindings=[...document.querySelectorAll('[data-bind]')];
let snapshot=null,received=0,failed=false,replayStart=null,seen=null,toasts=[],replaySeen=new Set(),releasePending=false,lastSeconds=0;
const listCache=new Map();
const time=at=>new Date(at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function bind(values){for(const el of bindings)if(el.dataset.bind in values)el.textContent=values[el.dataset.bind];}
function list(name,rows){const key=JSON.stringify(rows);if(listCache.get(name)===key)return;listCache.set(name,key);const template=$('template-'+name),alias=template.dataset.alias,root=$('list-'+name);root.replaceChildren();for(const row of rows){const fragment=template.content.cloneNode(true);const replace=s=>s.replace(/{{ (\w+)\.(\w+) }}/g,(_,a,k)=>a===alias?String(row[k]??''):'');const walker=document.createTreeWalker(fragment,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);while(walker.nextNode()){const n=walker.currentNode;if(n.nodeType===3)n.textContent=replace(n.textContent);else for(const attr of [...n.attributes])if(attr.value.includes('{{'))n.setAttribute(attr.name,replace(attr.value));}root.append(fragment);}}
function toast(event,accent){toasts.push({kind:event.kind,title:event.title,body:event.detail||event.body||'',time:time(event.at||new Date()),color:accent,expires:performance.now()+6500});toasts=toasts.slice(-3);if(replayStart===null&&'Notification'in window&&Notification.permission==='granted')new Notification(event.title,{body:event.detail||'',tag:'deadline-'+event.at});}
function draw(data,seconds,isReplay=false){const done=data.done||data.stage==='released',stage=STAGES.find(s=>s.key===data.stage)||STAGES[4],accent=done?'#7FB069':stage.color,h=seconds/3600;document.documentElement.style.setProperty('--accent',accent);document.documentElement.style.setProperty('--vignette',!done&&h<=.25?'inset 0 0 220px rgba(255,45,22,.16)':'none');document.documentElement.style.setProperty('--study-color',data.studyMinutesLogged>0?'#7FB069':'#D6452F');document.body.classList.toggle('released',done);
const liveLines={calm:'There is still time. Make it count.',nudging:'A little reminder goes a long way.',invasive:'Your calendar has a new priority.',hostile:'The excuses are running out.',armed:'Instagram is prepared. A human controls Share.'};
const draft=data.drafts.at(-1);bind({clockLabel:done?'Study watch complete':'Time until deadline',clock:done?'Well done.':[Math.floor(seconds/3600),Math.floor(seconds/60)%60,Math.floor(seconds)%60].map(n=>String(n).padStart(2,'0')).join(':'),stageName:data.stage,stageLine:done?'You did the work. Standing down.':data.stage==='fired'?'Deadline reached. A human still controls Share.':isReplay?stage.line:liveLines[data.stage]||stage.line,uptime:isReplay?'Presentation':data.deployment==='Steel Computer'?'Steel Computer':'Local session',vaultStatus:done?'released':data.liveViewUrl?'preview ready':data.photoReady?'sealed':'awaiting photo',caption:done?'Nothing to post. You did the work. I will find something else to worry about by tomorrow.':draft?.caption||'Your future self would like a word.',draftNo:String(data.drafts.length).padStart(2,'0'),draftAge:draft?time(draft.at):'—',statCal:data.mutations.filter(m=>!m.undone).length,statMail:data.emailsSent.length,statStudy:data.studyMinutesLogged||0,speedLabel:isReplay?'30-second replay · simulated activity':data.mode==='offline'?'Rehearsal · simulated integrations':'Live Google · real time'});
$('vault-count').textContent=data.photoReady?'1 photo held':'No photo selected';$('vault-photo').hidden=!data.photoReady;$('connection').textContent=isReplay?'Presentation only':failed?'Connection lost · clock paused':data.mode==='offline'?'Offline rehearsal':'Agent connected';$('warning').hidden=!data.pendingCount;$('warning').textContent=data.pendingCount?'An action needs attention. Check the agent before retrying.':'';
$('mark-done').hidden=isReplay||data.deployment!=='Steel Computer';$('mark-done').disabled=done||releasePending;$('viewer').hidden=done||isReplay||!data.liveViewUrl;if(data.liveViewUrl)$('viewer').href=data.liveViewUrl;else $('viewer').removeAttribute('href');
list('segments',STAGES.map(s=>({color:done?'#7FB069':s.color,fill:(Math.max(0,Math.min(1,(s.from-h)/(s.from-s.to)))*100)+'%',labelColor:h<=s.from?'#F2EFE9':'#5C5C57',label:s.key,range:s.key==='armed'?'final 15 min':s.key==='hostile'?'2h–15m':s.from+'–'+s.to+'h'})));
list('mutations',data.mutations.slice(-4).map(m=>({time:time(m.scheduledStart||m.at),from:m.undone?m.newTitle:m.originalTitle||'Free time',to:m.undone?m.originalTitle||'Study block removed':m.newTitle,color:m.undone?'#7FB069':'#F2EFE9'})));if(!data.mutations.length)$('list-mutations').textContent=done?'Calendar changes restored.':'No calendar changes yet.';
list('log',data.recentActivity.slice(0,6).map(e=>({time:time(e.at),text:e.title,color:e.kind==='restored'?'#7FB069':'#9A9A92'})));if(!data.recentActivity.length)$('list-log').textContent='Waiting for the first check-in.';
}
function accept(data){snapshot=data;received=performance.now();failed=false;const keys=new Set(data.recentActivity.map(e=>JSON.stringify(e)));if(seen&&replayStart===null)for(const e of data.recentActivity.slice().reverse())if(!seen.has(JSON.stringify(e)))toast(e,STAGES.find(s=>s.key===data.stage)?.color||'#EDE9E0');seen=keys;}
function renderReplay(){const seconds=Math.max(0,64800-(performance.now()-replayStart)*2.16),h=seconds/3600,stage=STAGES.find(s=>h<=s.from&&h>s.to)||STAGES[4],events=EVENTS.filter(e=>e.h>=h),cap=CAPTIONS.slice().reverse().find(c=>h<=c.h)||CAPTIONS[0],at=x=>new Date(Date.UTC(2026,0,1,12)-x*3600000).toISOString();for(const event of events)if(!replaySeen.has(event.h)){toast({...event,at:at(event.h)},stage.color);replaySeen.add(event.h);}draw({stage:seconds===0?'fired':stage.key,done:false,photoReady:snapshot?.photoReady||false,studyMinutesLogged:0,drafts:CAPTIONS.filter(c=>c.h>=h).map(c=>({caption:c.text,at:at(c.h)})),mutations:MUTATIONS.filter(m=>m.h>=h).map(m=>({at:at(m.h),originalTitle:m.from,newTitle:m.to,undone:false})),emailsSent:events.filter(e=>e.kind==='email'),recentActivity:events.slice().reverse().map(e=>({...e,at:at(e.h)}))},seconds,true);}
function tick(){if(replayStart!==null)renderReplay();else if(snapshot){const age=performance.now()-received;if(failed||age>5000){failed=true;}else lastSeconds=Math.max(0,Math.ceil((Date.parse(snapshot.deadlineISO)-Date.parse(snapshot.nowISO)-age*Number(snapshot.clockSpeed||1))/1000));draw(snapshot,lastSeconds);}toasts=toasts.filter(t=>t.expires>performance.now());list('toasts',toasts);}
async function poll(){try{const r=await fetch('/api/state',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();const d=await r.json();if(!Number.isFinite(Date.parse(d.deadlineISO))||!Number.isFinite(Date.parse(d.nowISO))||!Array.isArray(d.recentActivity))throw Error();accept(d);}catch{failed=true;if(replayStart===null)$('connection').textContent='Connection lost · clock paused';}finally{setTimeout(poll,1000);}}
$('replay').onclick=()=>{replayStart=replayStart===null?performance.now():null;replaySeen.clear();toasts=[];$('replay').textContent=replayStart===null?'Replay 18h in 30s':'Back to live agent';tick();};
$('notifications').onclick=async()=>{if(!('Notification'in window)){$('notifications').textContent='In-page alerts enabled';return;}const p=await Notification.requestPermission();$('notifications').textContent=p==='granted'?'Notifications enabled':'In-page alerts enabled';};
$('mark-done').onclick=async()=>{if(replayStart!==null||releasePending)return;releasePending=true;$('mark-done').disabled=true;$('mark-done').textContent='Restoring calendar…';try{const r=await fetch('/api/done',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error();$('mark-done').textContent='Released';}catch{$('mark-done').textContent='Release needs attention — check status';}};
poll();setInterval(tick,200);
