const $=id=>document.getElementById(id),presentation=location.pathname==='/canvas/presentation',base=presentation?'/canvas/presentation':'/canvas';let state;
const courses=[['First Year Hub','First Year Hub'],['PEY Co-op Resources Hub','ENG Cohort 6'],['APS105H1 S All Sections','APS105H1-S-LEC0103-20261'],['APS162H1 S LEC0101 20255:Calculus for Engineers I','APS162H1-S-LEC0101-20255'],['ECE - Undergraduate Office','ECE Undergraduate Office'],['ECE201H1 F LEC0101 20269:Electrical and Computer Engineering Seminar','ECE201H1-F-LEC0101-20269'],['ECE231H1 F LEC0101 20269:Introductory Electronics','ECE231H1-F-LEC0101-20269'],['ECE241H1 F LEC0101 20269:Digital Systems','ECE241H1-F-LEC0101-20269'],['MAT290H1 F LEC0102 20269:Advanced Engineering Mathematics','MAT290H1-F-LEC0102-20269'],['APS111H1 F LEC0101','Engineering Strategies and Practice']];
for(const [name,code]of courses){const a=document.createElement('a');a.href=presentation?base:'/canvas/assignment';a.textContent=name;const small=document.createElement('small');small.textContent=code;a.append(small);$('course-links').append(a);}
const assignment=presentation||location.pathname==='/canvas/assignment';$('dashboard-view').hidden=assignment;$('assignment-view').hidden=!assignment;$('reader').hidden=!assignment;$('tools').hidden=assignment;
if(assignment){$('breadcrumbs').innerHTML='<button id="course-menu" aria-label="Toggle course menu" style="border:0;background:white;color:#2379c5;font-size:24px">☰</button><a href="/canvas/courses">APS111H1 F LEC0101</a><span>›</span><a href="/canvas/assignment">Assignments</a><span>›</span> Teamwork Analysis';$('courses-button').classList.add('active');document.title='Teamwork Analysis · Canvas';$('course-menu').onclick=()=>document.querySelector('.course-nav').classList.toggle('collapsed');}else{$('breadcrumbs').innerHTML='<h1>Dashboard</h1>';document.querySelector('[data-nav="dashboard"]').classList.add('active');}
const notify=text=>{$('notice').textContent=text;$('notice').hidden=false;setTimeout(()=>$('notice').hidden=true,5000);};
$('courses-button').onclick=()=>{$('course-drawer').hidden=!$('course-drawer').hidden;};$('close-courses').onclick=()=>{$('course-drawer').hidden=true;};if(location.pathname==='/canvas/courses')$('course-drawer').hidden=false;
$('collapse').onclick=()=>document.body.classList.toggle('nav-collapsed');$('reader').onclick=()=>document.body.classList.toggle('reading');$('today').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});for(const id of ['todos','bell-button','add-todo','options'])$(id).onclick=()=>notify('Your assignment is available in Courses → APS111H1 → Assignments.');
for(const el of document.querySelectorAll('[data-panel]'))el.onclick=e=>{e.preventDefault();notify(el.dataset.panel==='Grades'?'This assignment has not been graded.':el.dataset.panel+' is not connected in this presentation environment.');};
$('office-hours').onclick=e=>{e.preventDefault();notify('LEC0102 office hours · See your course announcements for the schedule.');};$('planner-complete').onclick=()=>location.href='/canvas/assignment';
const fullDate=iso=>new Date(iso).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
async function refresh(){const r=await fetch(base+'/state',{cache:'no-store'});if(!r.ok)throw Error();state=await r.json();$('due').textContent=fullDate(state.deadline);$('overview-due').textContent=fullDate(state.deadline);$('planner-due').textContent='DUE: '+fullDate(state.deadline);$('submission-status').textContent=state.submitted?'✓ Submitted!':'Not Submitted!';$('submission-status').classList.toggle('success',state.submitted);$('submitted-at').textContent=state.submitted?fullDate(state.submission.submittedAt):'';$('download').hidden=!state.submitted;$('download').href=base+'/file';$('download').textContent=state.submitted?'Download '+state.submission.filename:'Download submission';$('show-submit').textContent=state.submitted?'Re-submit Assignment':'Submit Assignment';$('details').hidden=!state.submitted;}
$('show-submit').onclick=()=>{$('upload-panel').hidden=false;$('upload-panel').scrollIntoView({behavior:'smooth',block:'center'});};$('cancel-upload').onclick=()=>{$('upload-panel').hidden=true;};
$('submit').onclick=async()=>{const file=$('file').files[0];if(!file||!file.name.toLowerCase().endsWith('.pdf')||file.size>2*1024*1024){$('upload-status').textContent='Choose a PDF up to 2 MB.';return;}$('submit').disabled=true;$('upload-status').textContent='Submitting…';try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await fetch(base+'/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,data:btoa(binary)})});if(!r.ok){const d=await r.json();throw Error(d.error||'Submission failed');}await refresh();$('upload-panel').hidden=true;$('submission-comment').textContent=$('comment').value;notify('Assignment successfully submitted. Return to AMMA to verify it.');window.parent.postMessage({type:'amma-canvas-submitted'},location.origin);}catch(e){$('upload-status').textContent=e.message||'Connection lost. Check Submission Details before trying again.';}finally{$('submit').disabled=false;}};
$('details').onclick=e=>{e.preventDefault();notify(state?.submitted?'Submission received '+fullDate(state.submission.submittedAt)+'. File: '+state.submission.filename:'No submission found.');};$('rubric').onclick=e=>{e.preventDefault();notify('No rubric evaluation yet. AMMA verifies submission status; it does not grade the assignment.');};
refresh().catch(()=>notify('Canvas is unavailable. No submission status can be verified.'));
